name: zinc-plugin
version: '${version}'
main: com.github.zinc.ZincPlugin
api-version: 1.19
libraries:
  - io.github.monun:invfx-core:3.3.0
commands:
  status:
    aliases: '스테이터스'
    description: show your status
